title: Carlos Salgado, M.E.SC., B.Eng.
email: csalgado@uwo.com
description: >- # this means to ignore newlines until "baseurl:"
  Project portfolio of mechatronics engineer Carlos Salgado. Categories: Artificial Intelligence, Research, Software Development, Medical Image Processing, IoT, Cloud
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://socd06.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Team names, titles and social links
people:
- name: Carlos Salgado
  pic: 1
  position:
  social:
    - title: github
      url: http://github.com/socd06
    - title: linkedin
      url: https://www.linkedin.com/in/eng-socd/
    - title: envelope
      url: mailto:csalgado@uwo.ca

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
   - title: github
     url: http://github.com/socd06
   - title: linkedin
     url: https://www.linkedin.com/in/eng-socd/

# Postal address (add as many lines as necessary)
address:
  - line: London, ON
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
